//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public string PredictionLabelResult { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string MANAGEMENT_CULTURE { get; set; }
        public string HIRING_EFFECTIVITY { get; set; }
        public string TRAINING { get; set; }
        public string INFRASTRUCTURE { get; set; }
        public string MANAGEMENT_FEEDBACK { get; set; }
        public string INNOVATION_CULTURE { get; set; }
        public string MANAGEMENT_RESPECT { get; set; }
        public string ENVIR_HEALTHY { get; set; }
        public string SOCIAL_WORK_BALANCE { get; set; }
        public string BENEFITS { get; set; }
        public string PAY { get; set; }
        public string RECOGNITION { get; set; }
        public string CAREER_DEVELOPMENT { get; set; }
        public string NO_DISCRIMINATION { get; set; }
        public string OPEN_COMMUNICATION { get; set; }
        public string PURPOSE { get; set; }
        public string FELLOWSHIP { get; set; }
        public string CELEBRATION { get; set; }
        public string COLLABORATION_CULTURE { get; set; }
        public string PersonTitle { get; set; }
        public string CardId { get; set; }
        public string ProviderUserId { get; set; }
        public Nullable<System.DateTime> PredictionDate { get; set; }
    }
}
