//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalEvaluation
    {
        public int Id { get; set; }
        public string Pos { get; set; }
        public string Cons { get; set; }
        public string AdiceToPresident { get; set; }
        public string Recommend { get; set; }
        public string Rating { get; set; }
        public string Comment { get; set; }
        public string PredictionLabelResult { get; set; }
        public string UserProfile { get; set; }
        public string Source { get; set; }
        public string Comp_Benefits { get; set; }
        public string Work_Life_Balance { get; set; }
        public string Senior_Management { get; set; }
        public string Culture_Values { get; set; }
    }
}
