//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class PredictionLabel
    {
        public int Id { get; set; }
        public string Label { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Sentiment { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
